version: '3.8'
services:
  activity-service:
    build: ./activity-service
    container_name: activity-service
    ports:
      - "8083:8083"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    environment:
      - ACTIVITY_URL=http://activity-service:8083
    depends_on:
      - activity-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  employee-management-service:
    build: ./employee-management-service
    container_name: employee-management-service
    ports:
      - "8081:8081"
    environment:
      - NOTIFICATION_URL=http://notification-service:8082
      - ACTIVITY_URL=http://activity-service:8083
    depends_on:
      - notification-service
      - activity-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 